# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Blackout"
license = "MIT"
licenselink = "https://github.com/Blazin64/hugo-blackout/blob/master/LICENSE"
description = ""
homepage = "https://github.com/Blazin64/hugo-blackout/"
tags = ["blog","dark theme"]
features = ["pagination","syntax highlighting"]
min_version = "0.41"

[author]
  name = "Blazin64"
  homepage = "https://github.com/Blazin64/"
